<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>AttributeError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 3.6.5: /Users/alexanderChudinov/anaconda3/bin/python<br>Sat Mar 23 21:06:24 2019</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///Users/alexanderChudinov/Desktop/masseyhacks5/modelTrainer.py">/Users/alexanderChudinov/Desktop/masseyhacks5/modelTrainer.py</a> in <strong><module></strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;36</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#normalized_data&nbsp;=&nbsp;(data&nbsp;-&nbsp;minimum)&nbsp;/&nbsp;(maximum&nbsp;-&nbsp;minimum)<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;37</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;38</small>&nbsp;print(normalize(0))<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;39</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;40</small>&nbsp;model&nbsp;=&nbsp;Sequential()<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><em>builtin</em> <strong>print</strong>&nbsp;= &lt;built-in function print&gt;, <strong>normalize</strong>&nbsp;= &lt;function normalize&gt;</font></small></td></tr></table>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///Users/alexanderChudinov/Desktop/masseyhacks5/modelTrainer.py">/Users/alexanderChudinov/Desktop/masseyhacks5/modelTrainer.py</a> in <strong>normalize</strong>(column_id=0)</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;27</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;column&nbsp;=&nbsp;[]<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;28</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;x&nbsp;in&nbsp;range(len(X[0])):<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;29</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;column.push(X[x][column_id])<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;30</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmax&nbsp;=&nbsp;max(column)<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;31</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmin&nbsp;=&nbsp;min(column)<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><strong>column</strong>&nbsp;= [], column.push <em>undefined</em>, <em>global</em> <strong>X</strong>&nbsp;= array([[3.32000e+02, 2.24000e+02, 2.58000e+02, .... 3.18464e+05,
        7.20000e+01, 0.00000e+00]]), <strong>x</strong>&nbsp;= 0, <strong>column_id</strong>&nbsp;= 0</font></small></td></tr></table><p><strong>AttributeError</strong>: 'list' object has no attribute 'push'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
("'list' object has no attribute 'push'",)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=
&lt;built-in method with_traceback of AttributeError object&gt;


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "modelTrainer.py", line 38, in &lt;module&gt;
    print(normalize(0))
  File "modelTrainer.py", line 29, in normalize
    column.push(X[x][column_id])
AttributeError: 'list' object has no attribute 'push'

-->
